/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author moondem
 */
public class AddEmployee extends javax.swing.JFrame {
  ArrayList<Job> jobs;
    ArrayList<Employee> employee;
    DecimalFormat formatter;
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
         setLocationRelativeTo(null);
        
        formatter = new DecimalFormat("#,###.00");
        jobs = new ArrayList<Job>();
        employee = new ArrayList<Employee>();
        populateArrayList();
        
        String [] jobsArray = new String[jobs.size()];
//                = new String[] { "Item 1", "Item 2", "Item 3", "Item 4" };
        for(int i=0; i<jobs.size(); i++){
           jobsArray[i] = jobs.get(i).getNameOfJob() + ", ZMW "+ formatter.format(jobs.get(i).getSalary());
        }
        
        jobComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));
        
    }
    
   public void populateArrayList(){
       try{
           
           FileInputStream file = new FileInputStream("job.dat");
           ObjectInputStream inputFile = new ObjectInputStream(file);
           
           boolean endOfFile = false;
           while(!endOfFile){
             try{
                 jobs.add((Job)inputFile.readObject());
             
             }catch(EOFException e ){
                endOfFile = true;
             }catch(ClassNotFoundException fe){
              JOptionPane.showMessageDialog(null,fe.getMessage());
             }
           }
          inputFile.close();
          
       }catch(IOException f){
          JOptionPane.showMessageDialog(null,f.getMessage());
       }
       
       
        try{
           
           FileInputStream file2 = new FileInputStream("Employees.dat");
           ObjectInputStream inputFile2 = new ObjectInputStream(file2);
           
           boolean endOfFile = false;
           while(!endOfFile){
             try{
                 employee.add((Employee)inputFile2.readObject());
             
             }catch(EOFException e ){
                endOfFile = true;
             }catch(ClassNotFoundException fe){
              JOptionPane.showMessageDialog(null,fe.getMessage());
             }
           }
          inputFile2.close();
          
       }catch(IOException f){
          JOptionPane.showMessageDialog(null,f.getMessage());
       }
   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        empSurname = new javax.swing.JTextField();
        jobComboBox = new javax.swing.JComboBox<>();
        empStaffNum = new javax.swing.JTextField();
        saveEmployeeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add a new Employee by Entering the details below:");

        jLabel2.setText("Enter Employee Name:");

        jLabel3.setText("Enter Employee Surname:");

        jLabel4.setText("Choose a job:");

        jLabel5.setText("Enter the staff number:");

        jobComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        saveEmployeeBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveEmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/save.png"))); // NOI18N
        saveEmployeeBtn.setText("Save");
        saveEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empName)
                            .addComponent(empSurname)
                            .addComponent(jobComboBox, 0, 282, Short.MAX_VALUE)
                            .addComponent(empStaffNum)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(saveEmployeeBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(empStaffNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveEmployeeBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEmployeeBtnActionPerformed
        if(empName.getText().isEmpty() || empSurname.getText().isEmpty() ||
                empStaffNum.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Please enter all fields!");
        }else
        {
         String name = empName.getText().trim();
         String lastname = empSurname.getText().trim();
         int jobIndex = jobComboBox.getSelectedIndex();
         Job job = jobs.get(jobIndex);
          
         int staffNum = Integer.parseInt(empStaffNum.getText().trim());
         
         Employee emp = new Employee(name,lastname,job,staffNum);
         employee.add(emp);
         saveEmployeesToFile();
         
        }
        
    }//GEN-LAST:event_saveEmployeeBtnActionPerformed

    
       
   public void saveEmployeesToFile()
   {
       try
       {
           FileOutputStream file  = new FileOutputStream("Employees.dat");
           ObjectOutputStream outputFile = new ObjectOutputStream(file);
           
           for(int i=0; i<employee.size(); i++){
            outputFile.writeObject(employee.get(i));
           }
           
             outputFile.close();
             JOptionPane.showMessageDialog(null,"Successfully Saved!");
             this.dispose();
           
       }catch(IOException f)
       {
           JOptionPane.showMessageDialog(null,f.getMessage());
       }
   
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empName;
    private javax.swing.JTextField empStaffNum;
    private javax.swing.JTextField empSurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jobComboBox;
    private javax.swing.JButton saveEmployeeBtn;
    // End of variables declaration//GEN-END:variables
}
