/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author moondem
 */
public class EditEmployee extends javax.swing.JFrame {
    ArrayList<Job> jobs;
    ArrayList<Employee> employee;
    DecimalFormat formatter;
    /**
     * Creates new form EditEmployee
     */
    public EditEmployee() {
        initComponents();
        formatter = new DecimalFormat("#,###.00");
        jobs = new ArrayList<Job>();
        employee = new ArrayList<Employee>();
        populateArrayList();
        
        String [] jobsArray = new String[jobs.size()];
        String [] employeeArray = new String[employee.size()];
        
        //Get Employees registered in files
        for(int i=0; i<employee.size(); i++){
          employeeArray[i] = employee.get(i).getName() +" "
                  + ""+ employee.get(i).getSurname();
        }
//      // Get Jobs from file 
        for(int i=0; i<jobs.size(); i++){
           jobsArray[i] = jobs.get(i).getNameOfJob() + 
                   ", ZMW "+ formatter.format(jobs.get(i).getSalary());
        }
        
        jobCombox.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));
        empCombo.setModel(new javax.swing.DefaultComboBoxModel<>(employeeArray));
        
        empCombo.setSelectedIndex(0);
    }

       public void populateArrayList(){
       try{
           
           FileInputStream file = new FileInputStream("job.dat");
           ObjectInputStream inputFile = new ObjectInputStream(file);
           
           boolean endOfFile = false;
           while(!endOfFile){
             try{
                 jobs.add((Job)inputFile.readObject());
             
             }catch(EOFException e ){
                endOfFile = true;
             }catch(ClassNotFoundException fe){
              JOptionPane.showMessageDialog(null,fe.getMessage());
             }
           }
          inputFile.close();
          
       }catch(IOException f){
          JOptionPane.showMessageDialog(null,f.getMessage());
       }
       
       
        try{
           
           FileInputStream file2 = new FileInputStream("Employees.dat");
           ObjectInputStream inputFile2 = new ObjectInputStream(file2);
           
           boolean endOfFile = false;
           while(!endOfFile){
             try{
                 employee.add((Employee)inputFile2.readObject());
             
             }catch(EOFException e ){
                endOfFile = true;
             }catch(ClassNotFoundException fe){
              JOptionPane.showMessageDialog(null,fe.getMessage());
             }
           }
          inputFile2.close();
          
       }catch(IOException f){
          JOptionPane.showMessageDialog(null,f.getMessage());
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        empCombo = new javax.swing.JComboBox<>();
        jobCombox = new javax.swing.JComboBox<>();
        empSurname = new javax.swing.JTextField();
        empStaffNumber = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit Employee Data");

        jLabel2.setText("Choose Employee:");

        jLabel3.setText("Employee name:");

        jLabel4.setText("Employee surname:");

        jLabel5.setText("Employee job:");

        jLabel6.setText("Employee staff number:");

        empCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        empCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empComboActionPerformed(evt);
            }
        });

        jobCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        savebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/save.png"))); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/exit.png"))); // NOI18N
        jButton2.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jobCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empName)
                    .addComponent(empSurname)
                    .addComponent(empStaffNumber)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addComponent(empCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(empCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(empSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jobCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(empStaffNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empComboActionPerformed
        // TODO add your handling code here:
        int indexSelected = empCombo.getSelectedIndex();
//        employee
          empName.setText(employee.get(indexSelected).getName());
          empSurname.setText(employee.get(indexSelected).getSurname());
          empStaffNumber.setText(String.valueOf(employee.get(indexSelected).getStaffNr()));
          
          Job job = employee.get(indexSelected).getJob();
          
          int index = 0;
          for(int i=0; i< jobs.size(); i++)
          {
            if (jobs.get(i).equals(job))
            {
               index = i;
               System.out.println(index);
               break;
            }
          }
          
          
          jobCombox.setSelectedIndex(index);
          
    }//GEN-LAST:event_empComboActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
          if(empName.getText().isEmpty() || empSurname.getText().isEmpty() ||
                empStaffNumber.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Please enter all fields!");
        }else
        {
            int indexSelected = empCombo.getSelectedIndex();
            employee.get(indexSelected).setName((empName.getText().trim()));
            employee.get(indexSelected).setSurname((empSurname.getText().trim()));
            employee.get(indexSelected).setStaffNr((Integer.parseInt(empStaffNumber.getText().trim())));
            
            
//         String name = empName.getText().trim();
//         String lastname = empSurname.getText().trim();
//         int jobIndex = jobCombox.getSelectedIndex();
//         Job job = jobs.get(jobIndex);
//          
//         int staffNum = Integer.parseInt(empStaffNumber.getText().trim());
//         
//         Employee emp = new Employee(name,lastname,job,staffNum);
//         employee.add(emp);
//         saveEmployeesToFile();
//         
        }
        
    }//GEN-LAST:event_savebtnActionPerformed
   public void saveEmployeesToFile()
   {
       try
       {
           FileOutputStream file  = new FileOutputStream("Employees.dat");
           ObjectOutputStream outputFile = new ObjectOutputStream(file);
           
           for(int i=0; i<employee.size(); i++){
            outputFile.writeObject(employee.get(i));
           }
           
             outputFile.close();
             JOptionPane.showMessageDialog(null,"Successfully Saved!");
             this.dispose();
           
       }catch(IOException f){
           JOptionPane.showMessageDialog(null,f.getMessage());
       }
   
   }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> empCombo;
    private javax.swing.JTextField empName;
    private javax.swing.JTextField empStaffNumber;
    private javax.swing.JTextField empSurname;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jobCombox;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
