package Main;

/**
 *
 * @author moondem
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ExitBtn = new javax.swing.JMenu();
        exitBtn = new javax.swing.JMenuItem();
        addEmployeeBtn = new javax.swing.JMenu();
        addEmployee = new javax.swing.JMenuItem();
        ViewEmployees = new javax.swing.JMenuItem();
        addJobBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        EditEmployeeBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/men.png"))); // NOI18N

        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/folder.png"))); // NOI18N
        ExitBtn.setText("File");

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/exit.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        ExitBtn.add(exitBtn);

        jMenuBar1.add(ExitBtn);

        addEmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/add.png"))); // NOI18N
        addEmployeeBtn.setText("Add");

        addEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/addemployee.png"))); // NOI18N
        addEmployee.setText("Add Employee");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        addEmployeeBtn.add(addEmployee);

        ViewEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/addemployee.png"))); // NOI18N
        ViewEmployees.setText("View Employees");
        ViewEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmployeesActionPerformed(evt);
            }
        });
        addEmployeeBtn.add(ViewEmployees);

        addJobBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/job.png"))); // NOI18N
        addJobBtn.setText("Add Job");
        addJobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJobBtnActionPerformed(evt);
            }
        });
        addEmployeeBtn.add(addJobBtn);

        jMenuBar1.add(addEmployeeBtn);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/edit.png"))); // NOI18N
        jMenu3.setText("Edit");

        EditEmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/edit.png"))); // NOI18N
        EditEmployeeBtn.setText("Edit Employee");
        EditEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmployeeBtnActionPerformed(evt);
            }
        });
        jMenu3.add(EditEmployeeBtn);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addJobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJobBtnActionPerformed
         new AddNewJob().setVisible(true);
    }//GEN-LAST:event_addJobBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
       new AddEmployee().setVisible(true);
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void EditEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmployeeBtnActionPerformed
       new EditEmployee().setVisible(true);
    }//GEN-LAST:event_EditEmployeeBtnActionPerformed

    private void ViewEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmployeesActionPerformed
        // TODO add your handling code here:
        new ViewEmployees().setVisible(true);
    }//GEN-LAST:event_ViewEmployeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EditEmployeeBtn;
    private javax.swing.JMenu ExitBtn;
    private javax.swing.JMenuItem ViewEmployees;
    private javax.swing.JMenuItem addEmployee;
    private javax.swing.JMenu addEmployeeBtn;
    private javax.swing.JMenuItem addJobBtn;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
