/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moondem
 */
public class ViewEmployees extends javax.swing.JFrame {

    ArrayList<Job> jobs;
    ArrayList<Employee> employee;
    DecimalFormat formatter;

    /**
     * Creates new form ViewEmployees
     */
    public ViewEmployees() {
        initComponents();
        setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        formatter = new DecimalFormat("#,###.00");
        jobs = new ArrayList<Job>();
        employee = new ArrayList<Employee>();
        populateArrayList();

        String[] jobsArray = new String[jobs.size()];
//        String[] employeeArray = new String[employee.size()];

        //Get Employees registered in files
        for (int i = 0; i < employee.size(); i++) {
            //          employeeArray[i] = employee.get(i).getName()+" "
            //                  + ""+ employee.get(i).getSurname();
            Job job = employee.get(i).getJob();
            
            String[] employeeArray = {employee.get(i).getName(), employee.get(i).getSurname(),
                String.valueOf(employee.get(i).getStaffNr()), String.valueOf(job.getNameOfJob()), String.valueOf(job.getSalary())};
            
            model.addRow(employeeArray);
        }
//      // Get Jobs from file 
        for (int i = 0; i < jobs.size(); i++) {
            jobsArray[i] = jobs.get(i).getNameOfJob()
                    + ", ZMW " + formatter.format(jobs.get(i).getSalary());
        }

//        jobCombox.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));
//        empCombo.setModel(new javax.swing.DefaultComboBoxModel<>(employeeArray));
//        empCombo.setSelectedIndex(0);
    }

    public void populateArrayList() {
        try {

            FileInputStream file = new FileInputStream("job.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);

            boolean endOfFile = false;
            while (!endOfFile) {
                try {
                    jobs.add((Job) inputFile.readObject());

                } catch (EOFException e) {
                    endOfFile = true;
                } catch (ClassNotFoundException fe) {
                    JOptionPane.showMessageDialog(null, fe.getMessage());
                }
            }
            inputFile.close();

        } catch (IOException f) {
            JOptionPane.showMessageDialog(null, f.getMessage());
        }

        try {

            FileInputStream file2 = new FileInputStream("Employees.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2);

            boolean endOfFile = false;
            while (!endOfFile) {
                try {
                    employee.add((Employee) inputFile2.readObject());

                } catch (EOFException e) {
                    endOfFile = true;
                } catch (ClassNotFoundException fe) {
                    JOptionPane.showMessageDialog(null, fe.getMessage());
                }
            }
            inputFile2.close();

        } catch (IOException f) {
            JOptionPane.showMessageDialog(null, f.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Myriad Pro Regular", 1, 48)); // NOI18N
        jLabel1.setText("Employees");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "LastName", "Staff Number", "Job", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MacOs".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
